server:
    port: 9000
    ssl:
        key-store: keystore.p12
        key-store-password: {{ securityrat_keystore_password }}
        keyStoreType: PKCS12
        keyAlias: tomcat

liquibase:
    context: dev

spring:
    profiles:
        active: dev
    datasource:
        dataSourceClassName: com.mysql.jdbc.jdbc2.optional.MysqlDataSource
        url: jdbc:mysql://{{ securityrat_db_host }}:3306/{{ securityrat_db_name }}?useUnicode=true&characterEncoding=utf8
        databaseName: {{ securityrat_db_name }}
        serverName: {{ ansible_fqdn }}
        username: {{ securityrat_db_user }}
        password: {{ securityrat_db_password }}
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true

    jpa:
        database-platform: org.hibernate.dialect.MySQLInnoDBDialect
        database: MYSQL
        openInView: false
        show_sql: true
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: false
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
    data:
        elasticsearch:
            cluster-name:
            cluster-nodes:
            properties:
                path:
                  logs: target/elasticsearch/log
                  data: target/elasticsearch/data
    messages:
        cache-seconds: 1
    thymeleaf:
        mode: XHTML
        cache: false

metrics:
    jmx.enabled: true
    spark:
        enabled: false
        host: localhost
        port: 9999
    graphite:
        enabled: false
        host: localhost
        port: 2003
        prefix: sdlctool

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M

cas:
    casLoginUrl: https://localhost:8443/cas #Change to the URL your CAS server listens on
    casLogoutUrl: https://localhost:8443/cas/logout # Change to your CAS server logout URL
    callbackUrl: https://localhost:9000/callback #Change to the correct URL (https) of SecurityRAT
